version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    filename: logfile.log
    level: DEBUG
    formatter: simple
loggers:
  sampleLogger:
    level: DEBUG
    handlers: [console, file_handler]  # Add 'file_handler' here
    propagate: no
root:
  level: DEBUG
  handlers: [console, file_handler]  # Add 'file_handler' here
