{
 "title": "SCS-Health-Monitor",
 "description": "OpenStack scenario testing https://github.com/SovereignCloudStack/scs-health-monitor",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "mycmd", "label": "command", "query": { "query": "label_values(command)" } },
   {
    "name": "mymethod",
    "label": "method",
    "query": {
     "query": "label_values({command=\"$mycmd\"},method)"
    }
   },
   { "name": "mywait", "label": "resrc", "query": { "query": "label_values(command)" } },
   { "name": "mybench", "label": "bench", "query": { "query": "label_values(command)" } },
   {
    "name": "mycloud",
    "label": "cloud",
    "query": "gx, plus-pco, plus-prod2, plus-prod3, plus-prod4, stackit, wavestack1, cnds, aov, datapoc, ciab"
   },
   { "name": "mysvctype", "label": "service-type", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "title": "API calls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~'openstack_http_requests_total',cloud=\"$mycloud\",command=\"api-call\", method=~\".*\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "/^$mycloud$/",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "API errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~'openstack_http_requests_total',cloud=\"$mycloud\",command=\"api-call\", method=~\".*\", status_code=~\"(4|5).*\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "/^$mycloud$/",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "API success rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum({__name__=~'openstack_http_requests_total',cloud=\"$mycloud\",command=\"api-call\", method=~\".*\", status_code=~\"(4|5).*\"})/sum({__name__=~'openstack_http_requests_total',cloud=\"$mycloud\",command=\"api-call\", method=~\".*\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSH conns",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~'ssh_connections_total',cloud=\"$mycloud\",command=\"ssh\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "/^$mycloud$/",
     "query": "SELECT count(\"return_code\") FROM \"$mycloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=", "value": "ssh" }
     ]
    }
   ]
  },
  {
   "title": "SSH errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~'ssh_connections_total',cloud=~\"$mycloud\",command=~\"ssh\",status_code!~\"2..\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "/^$mycloud$/",
     "query": "SELECT sum(\"return_code\") FROM \"$mycloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=", "value": "ssh" }
     ]
    }
   ]
  },
  {
   "title": "SSH success rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "API falis",
     "expr": "sum({__name__=~'ssh_connections_total',status_code=~\"2..\",cloud=\"$mycloud\",command=~\"ssh\"})/sum({__name__=~'ssh_connections_total',cloud=\"$mycloud\",command=~\"ssh\"}) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "$mycloud",
     "query": "SELECT ((count(\"return_code\")-sum(\"return_code\"))/count(\"return_code\")) FROM \"$mycloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "Resrcs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$mycloud$/",
     "query": "SELECT count(\"return_code\") FROM \"$mycloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=~", "value": "/^$mywait$/" }
     ]
    }
   ]
  },
  {
   "title": "Resrc errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^$mycloud$/",
     "query": "SELECT sum(\"return_code\") FROM \"$mycloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=~", "value": "/^$mywait$/" }
     ]
    }
   ]
  },
  {
   "title": "Total test duration",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "API falis",
     "expr": "total_test_duration_seconds",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "$mycloud",
     "query": "SELECT ((count(\"return_code\")-sum(\"return_code\"))/count(\"return_code\")) FROM \"$mycloud\" WHERE (\"cmd\" = 'iperf3') AND $timeFilter",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "API errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_cmd $tag_method",
     "expr": "sum by(service_type, resource, status_code) (openstack_http_requests_total{status_code=~\"(4|5).*\", cloud=\"gx\",command=\"api-call\"}) > 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "command" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" }
     ],
     "legendFormat": "{{ service_type }} {{ resource }} ({{ status_code }})",
     "measurement": "/^$mycloud$/",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "Bench (ssh) errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "ERR($tag_cmd)",
     "expr": "{__name__=~'ssh_connections_total',cloud=~\"$mycloud\",command=~\"ssh\",status_code!~\"2..\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "command" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ host }}",
     "measurement": "/^$mycloud$/",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=~", "value": "/^$mybench$/" }
     ]
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Heatmap ssh connection time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "ssh_connect_duration_seconds_bucket{status_code=\"200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API response times",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_cmd $tag_method",
     "expr": "sum by(endpoint) (openstack_http_response_time_count{cloud=\"$mycloud\",command=\"api-call\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "command" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "/^$mycloud$/",
     "query": "SELECT \"duration\" FROM \"$mycloud\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "Bench connectivity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_cmd",
     "expr": "{__name__=~\"connectivity_tests_total\", cloud=\"$mycloud\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "command" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{command}} ({{ endpoint }})",
     "measurement": "/^$mycloud$/",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=~", "value": "/^$mybench$/" }
     ]
    }
   ]
  },
  {
   "title": "Bench iperf3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "targets": [
    {
     "alias": "$tag_cmd",
     "expr": "iperf3_bandwidth_receiver_gigabits{}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "command" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Bandwidth receiver ({{ sender_name }} -> {{ receiver_name }})",
     "measurement": "/^$mycloud$/",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=~", "value": "/^$mybench$/" }
     ]
    },
    {
     "alias": "$tag_cmd",
     "expr": "iperf3_bandwidth_sender_gigabits{}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "command" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Bandwidth sender ({{ sender_name }} -> {{ receiver_name }})",
     "measurement": "/^$mycloud$/",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=~", "value": "/^$mybench$/" }
     ]
    },
    {
     "expr": "iperf3_cpu_utilization_sender_percentage{}",
     "legendFormat": "CPU sender ({{ sender_name }} -> {{ receiver_name }})"
    },
    {
     "expr": "iperf3_cpu_utilization_receiver_percentage{}",
     "legendFormat": "CPU receiver ({{ sender_name }} -> {{ receiver_name }})"
    }
   ]
  },
  {
   "title": "Bench 4000pi calculation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "targets": [
    { "expr": "pi_calc_bench_avg_ping", "legendFormat": "{{value}}" }
   ]
  }
 ]
}