apiVersion: v1
kind: Service
metadata:
  name: export-grafana-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: my-kube-prometheus-stack
    app.kubernetes.io/name: grafana
  ports:
    - port: 3000
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 3000
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: export-grafana-push-gw-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: my-prometheus-pushgateway
    app.kubernetes.io/name: prometheus-pushgateway
  ports:
    - port: 9091
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 9091
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: export-prometheus-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: my-kube-prometheus-stack-prometheus
  ports:
    - port: 9090
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 9090
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30002
