{
 "title": "SCS-Health-Monitor",
 "description": "OpenStack scenario testing https://github.com/SovereignCloudStack/scs-health-monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "mycmd", "label": "cmd", "query": "show tag values with key = cmd" },
   {
    "name": "mymethod",
    "label": "method",
    "query": {
     "query": "show tag values with key = method where cmd =~ /$mycmd/"
    }
   },
   { "name": "mywait", "label": "Resrc", "query": "show tag values with key = cmd" },
   { "name": "mybench", "label": "Bench", "query": "show tag values with key = cmd" },
   {
    "name": "mycloud",
    "label": "Cloud",
    "query": "'.*gx.*',gx-scs, plus-pco, plus-prod2, plus-prod3, plus-prod4, stackit, wavestack1, cnds, aov, datapoc, ciab"
   }
  ]
 },
 "panels": [
  {
   "title": "API calls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg({__name__=~'openstack_http_requests_total',endpoint=~\".*gx.*\",cmd=~\".*\", method=~\".*\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "/^$mycloud$/",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "API errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(openstack_http_requests_total{status_code!~\"2..\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "/^$mycloud$/",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "API success rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "API falis",
     "expr": "count(openstack_http_requests_total{status_code=~\"2..\"})*100/count({__name__=~'openstack_http_requests_total',endpoint=~\".*gx.*\",cmd=~\".*\", method=~\".*\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "/^$mycloud$/",
     "query": "SELECT ((count(\"return_code\")-sum(\"return_code\"))/count(\"return_code\")) FROM \"$mycloud\" WHERE (\"cmd\" =~ /^$mycmd$/ AND \"method\" =~ /^$mymethod$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "ssh conns",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(gx-scs{cmd=\"ssh\"}[$__interval])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "/^$mycloud$/",
     "query": "SELECT count(\"return_code\") FROM \"$mycloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=", "value": "ssh" }
     ]
    }
   ]
  },
  {
   "title": "ssh errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^$mycloud$/",
     "query": "SELECT sum(\"return_code\") FROM \"$mycloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=", "value": "ssh" }
     ]
    }
   ]
  },
  {
   "title": "ssh success rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "API falis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "__auto",
     "measurement": "$mycloud",
     "query": "SELECT ((count(\"return_code\")-sum(\"return_code\"))/count(\"return_code\")) FROM \"$mycloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "Resrcs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$mycloud$/",
     "query": "SELECT count(\"return_code\") FROM \"$mycloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mywait$/" }
     ]
    }
   ]
  },
  {
   "title": "Resrc errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^$mycloud$/",
     "query": "SELECT sum(\"return_code\") FROM \"$mycloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mywait$/" }
     ]
    }
   ]
  },
  {
   "title": "iperf success rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "API falis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "$mycloud",
     "query": "SELECT ((count(\"return_code\")-sum(\"return_code\"))/count(\"return_code\")) FROM \"$mycloud\" WHERE (\"cmd\" = 'iperf3') AND $timeFilter",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "API errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_cmd $tag_method",
     "expr": "count by(endpoint) (openstack_http_requests_total{status!~\"2..\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "measurement": "/^$mycloud$/",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "Resource errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "$tag_cmd",
     "expr": "count by(job) (push_failure_time_seconds)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "/^$mycloud$/",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mywait$/" }
     ]
    }
   ]
  },
  {
   "title": "Bench (ssh) errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "ERR($tag_cmd)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$mycloud$/",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mybench$/" }
     ]
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "API response times",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_cmd $tag_method",
     "expr": "sum by(endpoint) (openstack_http_response_time_count)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "/^$mycloud$/",
     "query": "SELECT \"duration\" FROM \"$mycloud\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mycmd$/" },
      { "condition": "AND", "key": "method", "operator": "=~", "value": "/^$mymethod$/" }
     ]
    }
   ]
  },
  {
   "title": "Resource wait",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_cmd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$mycloud$/",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mywait$/" }
     ]
    }
   ]
  },
  {
   "title": "Bench",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_cmd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$mycloud$/",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^$mybench$/" }
     ]
    }
   ]
  }
 ]
}